mesd_presentation_homepage:
    path:     /
    defaults: { _controller: MesdPresentationBundle:Default:index }

mesd_presentation_heartbeat:
    path:     /heartbeat
    defaults: { _controller: MesdPresentationBundle:Default:heartbeat }
