MesdPresentationBundle_ui:
    resource: "@MesdPresentationBundle/Resources/config/routing/default.yml"
    prefix:   /ui

MesdPresentationBundle_docs:
    resource: "@MesdPresentationBundle/Resources/config/routing/docs.yml"
    prefix:   /docs
