MesdPresentationBundle_docs:
    resource: "@MesdPresentationBundle/Resources/config/routing/default.yml"
    prefix:   /

MesdPresentationBundle_docs:
    resource: "@MesdPresentationBundle/Resources/config/routing/docs.yml"
    prefix:   /docs

MesdPresentationBundle_displaysession:
    resource: "@MesdPresentationBundle/Resources/config/routing/displaySession.yml"
    prefix: /mesdpresentationdisplaysession
