MESDPresentationPresentationBundle_index:
    pattern: /
    defaults: { _controller: MESDPresentationPresentationBundle:Default:index }

MESDPresentationPresentationBundle_splash:
    pattern: /splash
    defaults: { _controller: MESDPresentationPresentationBundle:Default:splash }

MESDPresentationPresentationBundle_demo:
    pattern: /demo
    defaults: { _controller: MESDPresentationPresentationBundle:Default:demo }

# DEVELOPMENT
MESDPresentationPresentationBundle_dev_index:
    pattern: /dev
    defaults: { _controller: MESDPresentationPresentationBundle:Dev:index }

MESDPresentationPresentationBundle_dev_demo:
    pattern: /dev/demo
    defaults: { _controller: MESDPresentationPresentationBundle:Dev:demo }

MESDPresentationPresentationBundle_dev_flex:
    pattern: /dev/flex
    defaults: { _controller: MESDPresentationPresentationBundle:Dev:flex }

MESDPresentationPresentationBundle_dev_splash:
    pattern: /dev/splash
    defaults: { _controller: MESDPresentationPresentationBundle:Dev:splash }

MESDPresentationPresentationBundle_dev_collapse:
    pattern: /dev/collapse
    defaults: { _controller: MESDPresentationPresentationBundle:Dev:collapse }

MESDPresentationPresentationBundle_dev_tabcontent:
    pattern: /dev/tab
    defaults: { _controller: MESDPresentationPresentationBundle:Dev:tabcontent }