MesdPresentationBundle_index:
    pattern: /
    defaults: { _controller: MesdPresentationBundle:Default:index }

MesdPresentationBundle_docs:
    resource: "@MesdPresentationBundle/Resources/config/routing/docs.yml"
    prefix:   /docs

MesdPresentationBundle_splash:
    pattern: /splash
    defaults: { _controller: MesdPresentationBundle:Default:splash }

# Should login be split up?
# Such as: login, register, forgot-password, forgot-username
MesdPresentationBundle_login:
    pattern: /login
    defaults: { _controller: MesdPresentationBundle:Default:login }

MesdPresentationBundle_grid:
    pattern: /grid
    defaults: { _controller: MesdPresentationBundle:Default:grid }

# Should calendar be split up?
# Such as: calendar-month, calendar-week, calendar-day (agenda)
MesdPresentationBundle_calendar:
    pattern: /calendar
    defaults: { _controller: MesdPresentationBundle:Default:calendar }

MesdPresentationBundle_list:
    pattern: /list
    defaults: { _controller: MesdPresentationBundle:Default:list }

MesdPresentationBundle_map:
    pattern: /map
    defaults: { _controller: MesdPresentationBundle:Default:map }

MesdPresentationBundle_dashboard:
    pattern: /dashboard
    defaults: { _controller: MesdPresentationBundle:Default:dashboard }

MesdPresentationBundle_error:
    pattern: /error
    defaults: { _controller: MesdPresentationBundle:Default:error }

MesdPresentationBundle_profile:
    pattern: /profile
    defaults: { _controller: MesdPresentationBundle:Default:profile }

MesdPresentationBundle_help:
    pattern: /help
    defaults: { _controller: MesdPresentationBundle:Default:help }