MESDPresentationBundle_index:
    pattern: /
    defaults: { _controller: MESDPresentationBundle:Default:index }

MESDPresentationBundle_splash:
    pattern: /splash
    defaults: { _controller: MESDPresentationBundle:Default:splash }

MESDPresentationBundle_demo:
    pattern: /demo
    defaults: { _controller: MESDPresentationBundle:Default:demo }