parameters:
    presentation.config.class:       Mesd\PresentationBundle\Twig\ConfigExtension
    presentation.gravatar.class:     Mesd\PresentationBundle\Twig\GravatarExtension
    presentation.placeholder.class:  Mesd\PresentationBundle\Twig\PlaceholderExtension
    presentation.highlighter.class:  Mesd\PresentationBundle\Twig\HighlighterExtension
    presentation.interval.class:     Mesd\PresentationBundle\Twig\IntervalExtension
    presentation.breadcrumb.class:   Mesd\PresentationBundle\Twig\BreadcrumbExtension
    presentation.routeHelper.class:  Mesd\PresentationBundle\Twig\RouteHelperExtension

services:
    presentation.twig.config_extension:
        class: %presentation.config.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    presentation.twig.gravatar_extension:
        class: %presentation.gravatar.class%
        tags:
            - { name: twig.extension }

    presentation.twig.placeholder_extension:
        class: %presentation.placeholder.class%
        tags:
            - { name: twig.extension }

    presentation.twig.highlighter_extension:
        class: %presentation.highlighter.class%
        tags:
            - { name: twig.extension }

    presentation.twig.interval_extension:
        class: %presentation.interval.class%
        tags:
            - { name: twig.extension }

    presentation.twig.breadcrumb_extension:
        class: %presentation.breadcrumb.class%
        scope: container
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    presentation.twig.routeHelper_extension:
        class: %presentation.routeHelper.class%
        scope: container
        arguments: [@service_container]
        tags:
            - { name: twig.extension }