parameters:
    presentation.gravatar.class: MESD\Presentation\PresentationBundle\Twig\GravatarExtension
    presentation.placeholder.class: MESD\Presentation\PresentationBundle\Twig\PlaceholderExtension

services:
    presentation.twig.gravatar_extension:
        class: %presentation.gravatar.class%
        tags:
            - { name: twig.extension }

    presentation.twig.placeholder_extension:
        class: %presentation.placeholder.class%
        tags:
            - { name: twig.extension }