parameters:
    mesd_presentation.global_extension.class:     Mesd\PresentationBundle\Twig\GlobalExtension
    mesd_presentation.box_extension.class:        Mesd\PresentationBundle\Twig\BoxExtension
services:
    mesd_presentation.global_extension:
        class:     %mesd_presentation.global_extension.class%
        public:    false
        arguments: [ "%mesd_presentation%" ]
        tags:
            - { name: twig.extension }
    mesd_presentation.box_extension:
        class:     %mesd_presentation.box_extension.class%
        public:    false
        arguments: [ %mesd_presentation% ]
        tags:
            - { name: twig.extension }
