MesdPresentationBundle_docs_index:
    pattern: /
    defaults: { _controller: MesdPresentationBundle:Docs:toc }

MesdPresentationBundle_docs_toc:
    pattern: /toc
    defaults: { _controller: MesdPresentationBundle:Docs:toc }

MesdPresentationBundle_docs_grids:
    pattern: /grids
    defaults: { _controller: MesdPresentationBundle:Docs:grids }

MesdPresentationBundle_docs_type:
    pattern: /type
    defaults: { _controller: MesdPresentationBundle:Docs:type }

MesdPresentationBundle_docs_tables:
    pattern: /tables
    defaults: { _controller: MesdPresentationBundle:Docs:tables }

MesdPresentationBundle_docs_forms:
    pattern: /forms
    defaults: { _controller: MesdPresentationBundle:Docs:forms }

MesdPresentationBundle_docs_buttons:
    pattern: /buttons
    defaults: { _controller: MesdPresentationBundle:Docs:buttons }

MesdPresentationBundle_docs_img:
    pattern: /img
    defaults: { _controller: MesdPresentationBundle:Docs:img }

MesdPresentationBundle_docs_helpers:
    pattern: /helpers
    defaults: { _controller: MesdPresentationBundle:Docs:helpers }

MesdPresentationBundle_docs_icons:
    pattern: /icons
    defaults: { _controller: MesdPresentationBundle:Docs:icons }

MesdPresentationBundle_docs_navs:
    pattern: /navs
    defaults: { _controller: MesdPresentationBundle:Docs:navs }

MesdPresentationBundle_docs_breadcrumbs:
    pattern: /breadcrumbs
    defaults: { _controller: MesdPresentationBundle:Docs:breadcrumbs }

MesdPresentationBundle_docs_labels:
    pattern: /labels
    defaults: { _controller: MesdPresentationBundle:Docs:labels }